import { BLOCK } from './blocks.js';

// =============================================================================
// BIOMES
// =============================================================================
// Each biome describes how a single column should look (surface block, fluid,
// height noise, trees). Multi-biome worlds compose them along a single
// temperature axis T, with volcanic carved out of desert by a secondary noise.
//
// Logic:
//   T < -0.25  -> tundra (snowy, ice lakes)
//   -0.25 < T < 0.35 -> forest / plains (default)
//   T > 0.35   -> desert (sand, cactus, dunes)
//   inside desert, a separate "volcanic" noise patches in lava + obsidian
//
// All biomes share the same sea level so coastlines align. Differences come
// from height amplitude, offset, surface blocks, fluid and trees.
export const BIOMES = {
  forest: {
    id: 'forest',
    T: 0.0, // central temperate band
    seaLevel: 24,
    heightAmp: [8, 4, 9],
    heightFreq: [0.015, 0.05, 0.005],
    heightOffset: 1,
    surface: { top: BLOCK.GRASS, beach: BLOCK.SAND, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 5, type: 'oak' },
  },
  desert: {
    id: 'desert',
    T: 0.7, // hot
    seaLevel: 24,
    heightAmp: [9, 3, 6],
    heightFreq: [0.014, 0.05, 0.004],
    heightOffset: 4, // dunes stay above sea so it always reads as desert
    surface: { top: BLOCK.SAND, beach: BLOCK.SAND, sub: BLOCK.SAND, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: null,
    trees: { density: 2, type: 'cactus' },
  },
  tundra: {
    id: 'tundra',
    T: -0.7, // cold
    seaLevel: 24,
    heightAmp: [6, 3, 7],
    heightFreq: [0.015, 0.05, 0.005],
    heightOffset: 1,
    surface: { top: BLOCK.SNOW, beach: BLOCK.SNOW, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.ICE, level: 24 },
    trees: { density: 2, type: 'spruce' },
  },
  volcanic: {
    id: 'volcanic',
    // Volcanic lives INSIDE desert (same T) but is gated by a secondary noise
    // so it appears as patches in hot regions only.
    T: 0.7,
    seaLevel: 24,
    heightAmp: [11, 5, 6],
    heightFreq: [0.017, 0.06, 0.006],
    heightOffset: -1, // pits and ridges
    surface: { top: BLOCK.STONE, beach: BLOCK.STONE, sub: BLOCK.STONE, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.LAVA, level: 22 },
    trees: { density: 1, type: 'dead' },
  },
  swamp: {
    id: 'swamp',
    T: 0.1, // temperate-humid patch inside forest band
    seaLevel: 25,
    heightAmp: [4, 2, 4],
    heightFreq: [0.014, 0.05, 0.004],
    heightOffset: -1, // flatter and wetter than forest
    surface: { top: BLOCK.GRASS, beach: BLOCK.DIRT, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 25 },
    trees: { density: 4, type: 'oak' },
  },
  badlands: {
    id: 'badlands',
    T: 0.85, // hot-dry patch inside desert band
    seaLevel: 23,
    heightAmp: [10, 4, 7],
    heightFreq: [0.016, 0.055, 0.0045],
    heightOffset: 3,
    surface: { top: BLOCK.SAND_RED, beach: BLOCK.SAND_RED, sub: BLOCK.SAND_RED, deep: BLOCK.ROCK_GRANITE, bedrock: BLOCK.BEDROCK },
    fluid: null,
    trees: { density: 1, type: 'cactus' },
  },
  glacier: {
    id: 'glacier',
    T: -0.9, // very cold patch inside tundra band
    seaLevel: 24,
    heightAmp: [7, 3, 8],
    heightFreq: [0.016, 0.052, 0.005],
    heightOffset: 2,
    surface: { top: BLOCK.SNOW, beach: BLOCK.ICE, sub: BLOCK.ICE, deep: BLOCK.ROCK_MARBLE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.ICE, level: 24 },
    trees: { density: 1, type: 'spruce' },
  },
  meadow: {
    id: 'meadow',
    T: 0.0,
    seaLevel: 24,
    heightAmp: [6, 2, 6],
    heightFreq: [0.014, 0.045, 0.004],
    heightOffset: 1,
    surface: { top: BLOCK.GRASS, beach: BLOCK.DIRT, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 2, type: 'oak' },
  },
  cherry_grove: {
    id: 'cherry_grove',
    T: 0.05,
    seaLevel: 24,
    heightAmp: [7, 3, 7],
    heightFreq: [0.015, 0.05, 0.0045],
    heightOffset: 2,
    surface: { top: BLOCK.GRASS, beach: BLOCK.DIRT, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 4, type: 'oak' },
  },
  taiga: {
    id: 'taiga',
    T: -0.3,
    seaLevel: 24,
    heightAmp: [8, 3, 8],
    heightFreq: [0.015, 0.05, 0.005],
    heightOffset: 1,
    surface: { top: BLOCK.SNOW, beach: BLOCK.DIRT, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 5, type: 'spruce' },
  },
  savanna: {
    id: 'savanna',
    T: 0.5,
    seaLevel: 24,
    heightAmp: [7, 2, 6],
    heightFreq: [0.014, 0.045, 0.004],
    heightOffset: 3,
    surface: { top: BLOCK.GRASS, beach: BLOCK.SAND, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: null,
    trees: { density: 2, type: 'oak' },
  },
  jungle: {
    id: 'jungle',
    T: 0.45,
    seaLevel: 24,
    heightAmp: [10, 4, 9],
    heightFreq: [0.016, 0.052, 0.005],
    heightOffset: 2,
    surface: { top: BLOCK.GRASS, beach: BLOCK.DIRT, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 6, type: 'oak' },
  },
  bamboo_jungle: {
    id: 'bamboo_jungle',
    T: 0.5,
    seaLevel: 24,
    heightAmp: [8, 3, 8],
    heightFreq: [0.016, 0.05, 0.005],
    heightOffset: 2,
    surface: { top: BLOCK.GRASS, beach: BLOCK.DIRT, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 5, type: 'oak' },
  },
  mangrove: {
    id: 'mangrove',
    T: 0.35,
    seaLevel: 25,
    heightAmp: [5, 2, 5],
    heightFreq: [0.014, 0.05, 0.004],
    heightOffset: -1,
    surface: { top: BLOCK.GRASS, beach: BLOCK.DIRT, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 25 },
    trees: { density: 5, type: 'oak' },
  },
  mushroom_fields: {
    id: 'mushroom_fields',
    T: 0.1,
    seaLevel: 24,
    heightAmp: [6, 2, 5],
    heightFreq: [0.014, 0.045, 0.004],
    heightOffset: 1,
    surface: { top: BLOCK.ROCK_MARBLE, beach: BLOCK.ROCK_MARBLE, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 1, type: 'none' },
  },
  oasis: {
    id: 'oasis',
    T: 0.75,
    seaLevel: 24,
    heightAmp: [5, 2, 4],
    heightFreq: [0.013, 0.043, 0.004],
    heightOffset: 1,
    surface: { top: BLOCK.SAND, beach: BLOCK.SAND, sub: BLOCK.SAND, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 2, type: 'oak' },
  },
  mesa: {
    id: 'mesa',
    T: 0.85,
    seaLevel: 23,
    heightAmp: [11, 4, 8],
    heightFreq: [0.016, 0.055, 0.0045],
    heightOffset: 4,
    surface: { top: BLOCK.SAND_RED, beach: BLOCK.SAND_RED, sub: BLOCK.SAND_RED, deep: BLOCK.ROCK_GRANITE, bedrock: BLOCK.BEDROCK },
    fluid: null,
    trees: { density: 0, type: 'none' },
  },
  canyon: {
    id: 'canyon',
    T: 0.78,
    seaLevel: 22,
    heightAmp: [12, 5, 9],
    heightFreq: [0.017, 0.06, 0.005],
    heightOffset: 1,
    surface: { top: BLOCK.SAND_RED, beach: BLOCK.SAND, sub: BLOCK.SAND_RED, deep: BLOCK.ROCK_BASALT, bedrock: BLOCK.BEDROCK },
    fluid: null,
    trees: { density: 0, type: 'none' },
  },
  frozen_river: {
    id: 'frozen_river',
    T: -0.75,
    seaLevel: 24,
    heightAmp: [4, 2, 4],
    heightFreq: [0.014, 0.05, 0.004],
    heightOffset: -2,
    surface: { top: BLOCK.ICE, beach: BLOCK.ICE, sub: BLOCK.SNOW, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.ICE, level: 24 },
    trees: { density: 0, type: 'none' },
  },
  ice_spikes: {
    id: 'ice_spikes',
    T: -0.88,
    seaLevel: 24,
    heightAmp: [9, 4, 10],
    heightFreq: [0.017, 0.058, 0.005],
    heightOffset: 2,
    surface: { top: BLOCK.ICE, beach: BLOCK.ICE, sub: BLOCK.SNOW, deep: BLOCK.ROCK_MARBLE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.ICE, level: 24 },
    trees: { density: 0, type: 'none' },
  },
  dark_forest: {
    id: 'dark_forest',
    T: -0.05,
    seaLevel: 24,
    heightAmp: [9, 3, 8],
    heightFreq: [0.015, 0.052, 0.005],
    heightOffset: 1,
    surface: { top: BLOCK.GRASS, beach: BLOCK.DIRT, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 6, type: 'oak' },
  },
  flower_fields: {
    id: 'flower_fields',
    T: 0.05,
    seaLevel: 24,
    heightAmp: [5, 2, 5],
    heightFreq: [0.014, 0.045, 0.004],
    heightOffset: 1,
    surface: { top: BLOCK.GRASS, beach: BLOCK.DIRT, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 2, type: 'oak' },
  },
  rocky_peaks: {
    id: 'rocky_peaks',
    T: -0.1,
    seaLevel: 24,
    heightAmp: [13, 6, 12],
    heightFreq: [0.018, 0.06, 0.006],
    heightOffset: 4,
    surface: { top: BLOCK.STONE, beach: BLOCK.STONE, sub: BLOCK.STONE, deep: BLOCK.ROCK_BASALT, bedrock: BLOCK.BEDROCK },
    fluid: null,
    trees: { density: 0, type: 'none' },
  },
  stony_shore: {
    id: 'stony_shore',
    T: 0.0,
    seaLevel: 24,
    heightAmp: [6, 2, 6],
    heightFreq: [0.014, 0.05, 0.004],
    heightOffset: 0,
    surface: { top: BLOCK.STONE, beach: BLOCK.STONE, sub: BLOCK.STONE, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 1, type: 'none' },
  },
  basalt_delta: {
    id: 'basalt_delta',
    T: 0.82,
    seaLevel: 22,
    heightAmp: [10, 4, 8],
    heightFreq: [0.017, 0.06, 0.005],
    heightOffset: 1,
    surface: { top: BLOCK.ROCK_BASALT, beach: BLOCK.ROCK_BASALT, sub: BLOCK.ROCK_BASALT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.LAVA, level: 22 },
    trees: { density: 0, type: 'dead' },
  },
  crystal_plains: {
    id: 'crystal_plains',
    T: -0.2,
    seaLevel: 24,
    heightAmp: [7, 3, 7],
    heightFreq: [0.016, 0.05, 0.0045],
    heightOffset: 1,
    surface: { top: BLOCK.ROCK_MARBLE, beach: BLOCK.ICE, sub: BLOCK.ROCK_MARBLE, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 1, type: 'none' },
  },
  dry_wastes: {
    id: 'dry_wastes',
    T: 0.9,
    seaLevel: 22,
    heightAmp: [8, 3, 7],
    heightFreq: [0.015, 0.052, 0.0045],
    heightOffset: 3,
    surface: { top: BLOCK.SAND, beach: BLOCK.SAND, sub: BLOCK.SAND, deep: BLOCK.ROCK_GRANITE, bedrock: BLOCK.BEDROCK },
    fluid: null,
    trees: { density: 1, type: 'cactus' },
  },
};

// =============================================================================
// THEMES (server-side rooms)
// =============================================================================
// Two flavours of multi-biome worlds (Faction and Minage) share the same biome
// composition but use different seeds, so the maps are different but both
// contain all 4 biomes. Event is a calm single-biome creative-friendly world.
// PvP is a flat arena.
export const THEMES = {
  faction: {
    id: 'faction',
    name: 'Faction',
    mode: 'survival',
    tagline: 'Conquêtes et bases · mode survie',
    color: '#c43a3a',
    accent: '#ffb86b',
    seed: 'faction-2026',
    multiBiome: true,
    biomeFreq: 0.0010, // even wider biome regions
    sky: { rayleigh: 1.9, mieG: 0.83, turbidity: 9 },
    fog: { day: 0xb8d0e8, warm: 0xff9c6e, night: 0x070b1a },
    light: { hemiTop: 0xcfdcf0, hemiBottom: 0x6a4a2a, ambient: 0x2a2a30, sunHueShift: 0 },
    hotbar: [BLOCK.GRASS, BLOCK.DIRT, BLOCK.STONE, BLOCK.WOOD, BLOCK.PLANKS, BLOCK.GLASS, BLOCK.SAND, BLOCK.LEAVES, BLOCK.SNOW],
  },
  minage: {
    id: 'minage',
    name: 'Minage',
    mode: 'survival',
    tagline: 'Survie minière · creuse pour vivre',
    color: '#7a6648',
    accent: '#bfa980',
    seed: 'minage-2026',
    multiBiome: true,
    biomeFreq: 0.0012,
    sky: { rayleigh: 1.8, mieG: 0.8, turbidity: 8 },
    fog: { day: 0xc8d6e6, warm: 0xff9c6e, night: 0x080a14 },
    light: { hemiTop: 0xd8e2f0, hemiBottom: 0x4a3a2a, ambient: 0x252530, sunHueShift: 0 },
    hotbar: [BLOCK.STONE, BLOCK.DIRT, BLOCK.GRASS, BLOCK.WOOD, BLOCK.PLANKS, BLOCK.SAND, BLOCK.SNOW, BLOCK.GLASS, BLOCK.OBSIDIAN],
  },
  event: {
    id: 'event',
    name: 'Événement',
    mode: 'creative',
    tagline: 'Créatif · construis sans limite',
    color: '#a04abf',
    accent: '#f37cd2',
    seed: 'event-2026',
    seaLevel: 24,
    heightAmp: [4, 2, 6],
    heightFreq: [0.012, 0.04, 0.004],
    heightOffset: 0,
    surface: { top: BLOCK.GRASS, beach: BLOCK.SAND, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: { id: BLOCK.WATER, level: 24 },
    trees: { density: 6, type: 'oak' },
    sky: { rayleigh: 2.4, mieG: 0.86, turbidity: 7 },
    fog: { day: 0xe0c8ff, warm: 0xff9bd4, night: 0x100620 },
    light: { hemiTop: 0xeed4ff, hemiBottom: 0x6a4a8a, ambient: 0x301a40, sunHueShift: 0.02 },
    hotbar: [BLOCK.GRASS, BLOCK.PLANKS, BLOCK.GLASS, BLOCK.LEAVES, BLOCK.WOOD, BLOCK.STONE, BLOCK.WATER, BLOCK.SAND, BLOCK.LAVA],
  },
  pvp: {
    id: 'pvp',
    name: 'Mini-jeux & PvP',
    mode: 'creative',
    tagline: 'Arène plate · duels et parkour',
    color: '#1f2933',
    accent: '#ff5c5c',
    seed: 'pvp-2026',
    flat: true,
    flatHeight: 24, // top of grass
    surface: { top: BLOCK.GRASS, beach: BLOCK.SAND, sub: BLOCK.DIRT, deep: BLOCK.STONE, bedrock: BLOCK.BEDROCK },
    fluid: null,
    trees: { density: 0, type: 'none' },
    sky: { rayleigh: 1.4, mieG: 0.78, turbidity: 5 },
    fog: { day: 0xa8b8c8, warm: 0xff7060, night: 0x0a0a14 },
    light: { hemiTop: 0xc0c8d4, hemiBottom: 0x404a55, ambient: 0x202830, sunHueShift: 0 },
    hotbar: [BLOCK.STONE, BLOCK.PLANKS, BLOCK.WOOD, BLOCK.GLASS, BLOCK.LEAVES, BLOCK.GRASS, BLOCK.SAND, BLOCK.DIRT, BLOCK.BEDROCK],
  },
};

export function themeById(id) {
  return THEMES[id] || THEMES.faction;
}
